// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2944iBaf_qKIHgfifx-0K03gaC5Dl2Ek',
    appId: '1:888272419377:web:c114f169bf3a65c5553310',
    messagingSenderId: '888272419377',
    projectId: 'push-notification-767df',
    authDomain: 'push-notification-767df.firebaseapp.com',
    storageBucket: 'push-notification-767df.firebasestorage.app',
    measurementId: 'G-466TK8JZ3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVQ4oJVJOxGlb5MdVqSNR39tcETU8_mrc',
    appId: '1:888272419377:android:bcb57ec14bff98e8553310',
    messagingSenderId: '888272419377',
    projectId: 'push-notification-767df',
    storageBucket: 'push-notification-767df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlNoEDUret7ZD4ND8RYoA7DtHn6oV1pcs',
    appId: '1:888272419377:ios:61b075fb0bc23247553310',
    messagingSenderId: '888272419377',
    projectId: 'push-notification-767df',
    storageBucket: 'push-notification-767df.firebasestorage.app',
    iosBundleId: 'com.example.zker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlNoEDUret7ZD4ND8RYoA7DtHn6oV1pcs',
    appId: '1:888272419377:ios:61b075fb0bc23247553310',
    messagingSenderId: '888272419377',
    projectId: 'push-notification-767df',
    storageBucket: 'push-notification-767df.firebasestorage.app',
    iosBundleId: 'com.example.zker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2944iBaf_qKIHgfifx-0K03gaC5Dl2Ek',
    appId: '1:888272419377:web:e15e4970dcf5892e553310',
    messagingSenderId: '888272419377',
    projectId: 'push-notification-767df',
    authDomain: 'push-notification-767df.firebaseapp.com',
    storageBucket: 'push-notification-767df.firebasestorage.app',
    measurementId: 'G-548WFJ6SGB',
  );
}
